name: Windows Mocha Unit Tests

on:
  push:
    branches: [ main, os-test ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: Start-Job -Name "Server" {Set-Location $using:PWD; node .\server.js}; Start-Sleep -Seconds 1; Receive-Job -Name "Server"; npm test; Remove-Job -Name "Server" -Force
      shell: powershell
